// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pefszxifzxqiywchduah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlZnN6eGlmenhxaXl3Y2hkdWFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5MTc2NDgsImV4cCI6MjA4NzQ5MzY0OH0.wKX6fqxqBieGVp87qwkn_FsZ9pPJ_4HZdYCNbh7KBdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});