// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whlzqtupucxeqkaqmcds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndobHpxdHVwdWN4ZXFrYXFtY2RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwMDU4NjUsImV4cCI6MjA4NzU4MTg2NX0.5aheyRHAJPGRZxzzQlQI9WoAWVmjCRMM_5hGxOVqNac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});